### PR TITLE
1.4.2 - Fixes image paths on index pages (Issue #20)

### PR DESCRIPTION
**Pull request by twiro**
See https://github.com/symphonists/image_index_preview/issues/20#issuecomment-106266049 for details

### CODE REVIEW

**Comment by nitriques** [comment]
Could you rebase and resubmit against integration please ?

**Comment by twiro** [comment]
> _Could you rebase and resubmit against integration please ?_

Like so: https://github.com/symphonists/image_index_preview/pull/23 ?
Or should I better have updated this PR? (Didn't know how)

**Comment by twiro** [comment]
This PR can be closed/deleted in Favor of https://github.com/symphonists/image_index_preview/pull/23

**Comment by nitriques** [comment]
Ok Thanks!

**Pull request closed without merging**
